POST http://localhost:3000/auth/signup
content-type: application/json

{
	"email": "test2@test.com",
	"password": "password123"
}

### BAD POST email
POST http://localhost:3000/auth/signup
content-type: application/json

{
	"email": "tkldjdlkjio",
	"password": "password123"
}

### BAD POST password
POST http://localhost:3000/auth/signup
content-type: application/json

{
	"email": "test@test.com",
	"password": 5
}

### GET A User With a Particular ID
GET http://localhost:3000/auth/2

### GET A User WIth a Particular Email
GET http://localhost:3000/auth?email=test2@test.com

### DELETE A User WITH a Given Id
DELETE http://localhost:3000/auth/1

### UPDATE A User Email
PATCH http://localhost:3000/auth/2
content-type: application/json

{
	"password": 4
}